trigger:
  branches:
    include:
      - main
      - develop

pool:
  # vmImage: 'ubuntu-latest'
  name: Default

variables:
  javaVersion: '21'
  
steps:
  - script: mvn -B clean package -DskipTests
    displayName: 'Build Maven'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'drop'            

  - task: AzureWebApp@1          
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: 'sc-raizdobem-backend'
      appName: 'raizdobem-backend'
      package: '$(System.DefaultWorkingDirectory)/drop/quarkus-app'