quarkus.swagger-ui.theme=original

quarkus.smallrye-openapi.info-title=Raiz do Bem
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Projeto academico elaborado para o Challenge FIAP 2025-26

quarkus.datasource.db-kind=oracle
quarkus.datasource.username=system
quarkus.datasource.password=123
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1