#CoresSwaggerOriginal
quarkus.swagger-ui.theme=original
quarkus.swagger-ui.always-include=true

#InformaçõesTelaSwagger
quarkus.smallrye-openapi.info-title=Raiz do Bem
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Projeto academico elaborado para o Challenge FIAP 2025-26

#InfosBancoDados
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=${DB_USUARIO}
quarkus.datasource.password=${DB_SENHA}
quarkus.datasource.jdbc.url=${DB_URL}

#InicioUrl
quarkus.rest-client.via-cep-api.url=https://viacep.com.br/ws
quarkus.rest-client.google-maps-api.url=https://routes.googleapis.com
google-api-key=${GOOGLE_API_KEY}

#CORS
quarkus.http.cors.enabled=true
#quarkus.http.cors.origins=https://raiz-do-ltzpugru3-renans-projects-d48bb743.vercel.app
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE,PATCH,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type
quarkus.http.cors.access-control-max-age=24H

#Autenticação JWT
mp.jwt.verify.publickey.location=keyPublica.pem
mp.jwt.verify.issuer=raiz-do-bem
smallrye.jwt.sign.key.location=keyPrivada.pem

quarkus.http.auth.proactive=false
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=bearerAuth