quarkus.swagger-ui.theme=original

quarkus.smallrye-openapi.info-title=Raiz do Bem
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Projeto academico elaborado para o Challenge FIAP 2025-26

quarkus.datasource.db-kind=oracle
quarkus.datasource.username=system
quarkus.datasource.password=123
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1

quarkus.rest-client.via-cep-api.url=https://viacep.com.br/ws

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization


# Em produção, trocar origins=* por seu domínio específico:
# quarkus.http.cors.origins=https://raizdobem.azurewebsites.net